---
- name: Install Apache and upload WebPage
  hosts: "all"
  become: yes
  vars:
    source_file: /home/andrey/.ansible/
    destination_file: /var/www/html/
  tasks:
    - block: #For Ubuntu
      - name: Install Apache to Ubuntu
        apt:
          name: apache2
          state: latest
      - name: start Webserv
        service: name=apache2 state=started
      when: ansible_os_family == "Debian"
    - block: #For RedHat
      - name: Install Apache to Centos
        yum: name=httpd state=latest
      - name: Запустим Apache
        service:
          name: httpd
          state: started
      when: ansible_os_family == "RedHat"

    - name: Copy WebPage to serv
      template: src={{ source_file }}/index.j2 dest={{ destination_file }}/index.html
      become: yes
      notify:
       - restart apache Debian
       - restart apache RedHat
  handlers:
    - name: restart apache Debian
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"
    - name: restart apache RedHat
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: ansible_os_family == "RedHat"
