---
# handlers file for deploy_Apache
- name: restart apache Debian
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"
- name: restart apache RedHat
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"
